# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog.resize(400, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 340))
        Dialog.setMaximumSize(QtCore.QSize(400, 340))
        Dialog.setModal(True)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 0, 271, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.about__label_title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.about__label_title.setMinimumSize(QtCore.QSize(20, 20))
        self.about__label_title.setLineWidth(1)
        self.about__label_title.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.about__label_title.setObjectName("about__label_title")
        self.horizontalLayout_3.addWidget(self.about__label_title)
        self.label_version = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_version.setMinimumSize(QtCore.QSize(0, 20))
        self.label_version.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTop | QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_3.addWidget(self.label_version)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.label_copyright = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_copyright.sizePolicy().hasHeightForWidth())
        self.label_copyright.setSizePolicy(sizePolicy)
        self.label_copyright.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_copyright.setWordWrap(True)
        self.label_copyright.setObjectName("label_copyright")
        self.verticalLayout_5.addWidget(self.label_copyright)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.label_description = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_description.sizePolicy().hasHeightForWidth())
        self.label_description.setSizePolicy(sizePolicy)
        self.label_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.verticalLayout_2.addWidget(self.label_description)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_contacts = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_contacts.setObjectName("label_contacts")
        self.verticalLayout_4.addWidget(self.label_contacts)
        self.label_email = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_email.sizePolicy().hasHeightForWidth())
        self.label_email.setSizePolicy(sizePolicy)
        self.label_email.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.label_email.setAutoFillBackground(False)
        self.label_email.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_email.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_email.setLineWidth(1)
        self.label_email.setMidLineWidth(1)
        self.label_email.setText("olegandreev_bern@gmail.com")
        self.label_email.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_email.setOpenExternalLinks(True)
        self.label_email.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_email.setObjectName("label_email")
        self.verticalLayout_4.addWidget(self.label_email)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.about__icon = QtWidgets.QFrame(Dialog)
        self.about__icon.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.about__icon.setMinimumSize(QtCore.QSize(100, 100))
        self.about__icon.setMaximumSize(QtCore.QSize(100, 100))
        self.about__icon.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.about__icon.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.about__icon.setObjectName("about__icon")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 190, 271, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(10, 0, 10, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_notes_p2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_notes_p2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_notes_p2.setWordWrap(True)
        self.label_notes_p2.setIndent(1)
        self.label_notes_p2.setObjectName("label_notes_p2")
        self.verticalLayout_3.addWidget(self.label_notes_p2)
        self.label_disclaimer = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_disclaimer.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_disclaimer.setWordWrap(True)
        self.label_disclaimer.setIndent(0)
        self.label_disclaimer.setObjectName("label_disclaimer")
        self.verticalLayout_3.addWidget(self.label_disclaimer)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 121, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_SN_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_SN_title.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_SN_title.setObjectName("label_SN_title")
        self.verticalLayout.addWidget(self.label_SN_title)
        self.label_SN = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_SN.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_SN.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_SN.setObjectName("label_SN")
        self.verticalLayout.addWidget(self.label_SN)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "О программе"))
        self.about__label_title.setText(_translate("Dialog", "Застропи ЭТО"))
        self.label_version.setText(_translate("Dialog", "Версия: 1.0.0"))
        self.label_copyright.setText(_translate("Dialog", "Copyright © 2022 Fermata Prod. (Oleg Andreev)"))
        self.label_description.setText(
            _translate("Dialog", "Программа предназначена для расчета типовых схем строповки грузов."))
        self.label_contacts.setText(_translate("Dialog", "По всем вопросам обращаться:"))
        self.label_email.setToolTip(_translate("Dialog", "Отправить email на указанный адрес"))
        self.label_notes_p2.setText(_translate("Dialog",
                                               "Для расчета нетиповых схем строповки данная программа не применяется (например, груз имеет смещенный центр тяжести, несимметричное расположение точек крепления и пр.)"))
        self.label_disclaimer.setText(_translate("Dialog",
                                                 "Использование расчетов, выполненных данной программой, Вы осуществляете на свой страх и риск!"))
        self.label_SN_title.setText(_translate("Dialog", "Серийный номер:"))
        self.label_SN.setText(_translate("Dialog", "1234-5678-1234"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
